# Generated by Django 5.0.3 on 2024-03-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('marks1', models.IntegerField()),
                ('marks2', models.IntegerField()),
                ('marks3', models.IntegerField()),
                ('marks4', models.IntegerField()),
            ],
        ),
    ]
